name: Java gradle CI
# run-name: ${{ github.actor }}

on:
  pull_request:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest

# jdk setting
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: 'gradle'
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        
      - name: Test with Gradle
        run: ./gradlew test --no-daemon
